FROM python:3.4-alpine
RUN pip install --upgrade pip
RUN pip install nose coverage nosexcover pylint
RUN mkdir /home/demo
WORKDIR /home/demo
ENTRYPOINT ["nosetests", "--with-xunit", "--xunit-file=nosetests.xml" "--with-xcoverage", "--xcoverage-file=coverage.xml", "-sv"]

